# Generated by Django 4.1.1 on 2022-10-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران خبرنامه'},
        ),
    ]
