# Generated by Django 4.1.2 on 2022-10-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_desc_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc_short',
            field=models.CharField(max_length=100, verbose_name='توضیح کوتاه'),
        ),
    ]
