# Generated by Django 4.1.2 on 2022-11-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'درخواست تماس با ما', 'verbose_name_plural': 'درخواست های تماس با ما'},
        ),
        migrations.AlterField(
            model_name='post',
            name='off_time',
            field=models.CharField(blank=True, choices=[('1', 'صبح'), ('2', 'ظهر'), ('3', 'عصر'), ('4', 'شب')], max_length=1, verbose_name='زمان تخفیف'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=128, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyvalue',
            unique_together={('property', 'value')},
        ),
    ]
