# Generated by Django 4.1.2 on 2023-12-14 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_alter_contact_options_alter_post_off_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-avail", "-id"],
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
    ]
